version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker: 
      - image: circleci/node:7-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build-web
      